---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dieter Stockhausen.
--- Date: 29.10.2023
---
local LrLogger = import("LrLogger")
local _logger = LrLogger("EditionDetailsLrLogger")
_logger:enable("logfile")
local enabled = true
-------------------------------------------------------------------------------
local logger = {}
-------------------------------------------------------------------------------
function logger.trace(msg)
    if (enabled) then
        _logger:trace(msg)
    end
end
-------------------------------------------------------------------------------
return logger